from collections import Counter
from pathlib import Path
import json

OPEN_TO_CLOSE = {"(": ")", "[": "]"}
CLOSE_TO_OPEN = {")": "(", "]": "["}


def is_valid_dyck_stack(s: str) -> bool:
    """
    Deterministic pushdown automaton baseline for Dyck membership.

    Returns True if s is a valid balanced bracket string over () and [].
    """
    stack = []

    for ch in s:
        if ch in OPEN_TO_CLOSE:
            stack.append(ch)

        elif ch in CLOSE_TO_OPEN:
            if not stack:
                return False

            opener = stack.pop()

            if OPEN_TO_CLOSE[opener] != ch:
                return False

        else:
            return False

    return len(stack) == 0


def predict_is_error(s: str) -> int:
    """
    Predict whether a string contains an error.

    Return:
        0 if valid Dyck string
        1 if invalid Dyck string
    """
    return 0 if is_valid_dyck_stack(s) else 1


def load_jsonl(path: str | Path) -> list[dict]:
    path = Path(path)

    with path.open("r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def evaluate_baseline(path: str | Path) -> dict:
    """
    Evaluate stack baseline on a JSONL dataset generated by src/data.py.
    """
    examples = load_jsonl(path)

    total = len(examples)
    correct = 0

    by_error_type = Counter()
    correct_by_error_type = Counter()

    for ex in examples:
        gold = ex["is_error"]
        pred = predict_is_error(ex["input_string"])
        error_type = ex["error_type"]

        by_error_type[error_type] += 1

        if pred == gold:
            correct += 1
            correct_by_error_type[error_type] += 1

    accuracy = correct / total if total > 0 else 0.0

    per_type_accuracy = {
        error_type: correct_by_error_type[error_type] / count
        for error_type, count in by_error_type.items()
    }

    return {
        "total": total,
        "correct": correct,
        "accuracy": accuracy,
        "per_type_accuracy": per_type_accuracy,
    }


if __name__ == "__main__":
    test_strings = [
        "",
        "()",
        "[]",
        "([])",
        "[()]",
        "()[]",
        "([)]",
        "(()",
        "())",
        "][",
        "([]]",
    ]

    for s in test_strings:
        print(
            {
                "string": s,
                "valid": is_valid_dyck_stack(s),
                "predicted_is_error": predict_is_error(s),
            }
        )

    print("Baseline sanity checks passed.")